# Generated by Django 5.0.4 on 2024-05-15 17:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment_suggestions', models.TextField()),
                ('image', models.ImageField(upload_to='diseases')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_type', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='plants')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image_status', models.CharField(choices=[('Processing', 'Processing'), ('Processed', 'Processed')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('confidence_level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.disease')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.image')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.plant')),
            ],
        ),
    ]
