# Generated by Django 5.0.1 on 2024-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pH', models.FloatField()),
                ('nutrient_levels', models.CharField(max_length=100)),
                ('light_intensity', models.CharField(max_length=100)),
                ('water_requirement', models.CharField(max_length=100)),
                ('irrigation_amount', models.FloatField()),
                ('nutrient_supply', models.CharField(max_length=100)),
                ('plant_condition', models.CharField(max_length=50)),
                ('harvest_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=50)),
                ('optimal_temperature_range', models.CharField(max_length=50)),
                ('optimal_humidity_range', models.CharField(max_length=50)),
                ('optimal_nutrient_levels', models.CharField(max_length=100)),
                ('light_requirement', models.CharField(max_length=100)),
                ('water_requirement', models.CharField(max_length=100)),
                ('susceptibility_to_diseases', models.TextField()),
                ('harvest_time', models.CharField(max_length=50)),
            ],
        ),
    ]
