# Generated by Django 5.0.3 on 2025-05-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255, unique=True)),
                ('common_name_hu', models.CharField(max_length=255)),
                ('pathogen', models.CharField(max_length=255)),
                ('type', models.TextField()),
                ('identification', models.TextField()),
                ('solutions', models.TextField()),
                ('host', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_name', models.CharField(max_length=255, unique=True)),
                ('common_name', models.CharField(max_length=255, unique=True)),
                ('family', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('uses', models.TextField()),
                ('distribution', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
