# Generated by Django 5.0.3 on 2025-03-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latin_name', models.CharField(max_length=255, unique=True)),
                ('family', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('native_region', models.TextField()),
                ('uses', models.TextField()),
                ('distribution', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latin_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('causes', models.TextField()),
                ('treatment', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, 'Enyhe'), (2, 'Mérsékelt'), (3, 'Súlyos')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
            ],
        ),
    ]
