# Generated by Django 5.2.1 on 2025-05-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['common_name'], name='plant_disea_common__3371b0_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['pathogen'], name='plant_disea_pathoge_b5d6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['common_name'], name='plant_plant_common__d4d233_idx'),
        ),
    ]
