# Generated by Django 5.0.3 on 2025-04-04 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdisease',
            old_name='latin_name',
            new_name='botanical_name',
        ),
        migrations.RenameField(
            model_name='plantdisease',
            old_name='name',
            new_name='common_name',
        ),
        migrations.RenameField(
            model_name='plantdisease',
            old_name='causes',
            new_name='identification',
        ),
        migrations.RenameField(
            model_name='plantdisease',
            old_name='description',
            new_name='solutions',
        ),
        migrations.RenameField(
            model_name='plantdisease',
            old_name='treatment',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='plantdisease',
            name='severity',
        ),
        migrations.AddField(
            model_name='plantdisease',
            name='host',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
