# Generated by Django 5.0.3 on 2025-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_rename_latin_name_plantdisease_botanical_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdisease',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
