# Generated by Django 5.0.3 on 2025-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plantdisease_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='latin_name',
            new_name='botanical_name',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='common_name',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='native_region',
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
