# Generated by Django 5.0.3 on 2025-04-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_rename_latin_name_plant_botanical_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantDisease',
            new_name='Disease',
        ),
    ]
