# Generated by Django 5.0.3 on 2025-05-07 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_uploads/')),
                ('image_status', models.CharField(choices=[('Feltöltve', 'Feltöltve'), ('Feldolgozva', 'Feldolgozva'), ('Hiba', 'Hiba')], default='Feltöltve', max_length=20)),
                ('image_type', models.CharField(choices=[('disease', 'disease'), ('plant', 'plant')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_plant', models.CharField(max_length=100)),
                ('detected_disease', models.CharField(blank=True, max_length=100)),
                ('plant_confidence_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disease_confidence_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recognition.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
