# Generated by Django 5.0.3 on 2025-03-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionresult',
            name='detected_disease',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recognitionresult',
            name='detected_plant',
            field=models.CharField(max_length=50),
        ),
    ]
