# Generated by Django 5.2.1 on 2025-05-09 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['user'], name='recognition_user_id_f7966b_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_type'], name='recognition_image_t_c80e29_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='recognition_created_ab40bb_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['image'], name='recognition_image_i_8d33bf_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['detected_plant'], name='recognition_detecte_cb780c_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['detected_disease'], name='recognition_detecte_5654ec_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['created_at'], name='recognition_created_167c38_idx'),
        ),
    ]
