# Generated by Django 5.0.3 on 2025-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_recognitionresult_detected_disease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='image',
            name='processed_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='Uploaded', max_length=20),
        ),
    ]
