# Generated by Django 5.0.3 on 2025-04-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_alter_result_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_status',
            field=models.CharField(choices=[('Feltöltve', 'Feltöltve'), ('Feldolgozva', 'Feldolgozva'), ('Hiba', 'Hiba')], default='Feltöltve', max_length=20),
        ),
    ]
